options:
    # Don't merge default rules
    merge-default-rules: false
    # Raise an error if more than 50 warnings are generated
    max-warnings: 50
# File Options
files:
    include: 'html/scss/*.scss'
    ignore:
        - 'html/scss/vendor/**/*.*'
# Rule Configuration
rules:
    class-name-format:
        - 2
        -
            convention: hyphenatedbem
    mixin-name-format:
        - 2
        -
            convention: hyphenatedlowercase
    extends-before-mixins: 2
    extends-before-declarations: 2
    declarations-before-nesting: 2
    placeholder-in-extend: 2
    no-color-keywords: 2
    no-duplicate-properties: 2
    no-empty-rulesets: 2
    no-misspelled-properties: 2
    no-trailing-whitespace: 2
    no-trailing-zero: 2
    one-declaration-per-line: 2
    single-line-per-selector: 2
    pseudo-element: 2
    space-after-bang: 2
    space-after-colon: 2
    space-after-comma: 2
    space-around-operator: 2
    space-before-bang: 2
    space-before-brace: 2
    space-before-colon: 2
    space-between-parens: 2
    trailing-semicolon: 2
    url-quotes: 2
    zero-unit: 2
    variable-name-format:
        - 2
        -
            convention: hyphenatedlowercase
    empty-line-between-blocks:
        - 2
        -
            include: true
    final-newline:
        - 2
        -
            include: true
    mixins-before-declarations:
        - 2
        -
            exclude:
                - breakpoint
                - mq
    nesting-depth:
        - 2
        -
            max-depth: 2
    no-warn: 1
    no-debug: 1
    no-ids: 2
    no-important: 2
    hex-notation:
        - 2
        -
            style: uppercase
    indentation:
        - 2
        -
            size: 4
    quotes:
        - 2
        -
            style: single
    property-sort-order:
        - 2
        -
            order:
                - display
                - margin
            ignore-custom-properties: true
    variable-for-property:
        - 2
        -
            properties:
                - margin
